import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const neueLight = localFont({
  src : './fonts/NeueMachina-Light.otf',
  variable: "--font-neue-light",
  weight : "400"
})

const neueRegular = localFont({
  src : './fonts/NeueMachina-Regular.otf',
  variable: "--font-neue-regular",
  weight : "500"
})

const neueBold = localFont({
  src : './fonts/NeueMachina-Bold.woff',
  variable: "--font-neue-bold",
  weight : "800"
})

const neueUltraBold = localFont({
  src : './fonts/NeueMachina-Ultrabold.otf',
  variable: "--font-neue-ultrabold",
  weight : "800"
})

export const metadata: Metadata = {
  title: "MoonEx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${neueLight.variable} ${neueRegular.variable} ${neueBold.variable} ${neueUltraBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
